"""Wu Blockchain BTC daily indicators and human-readable interpretation rules.

Thresholds in this file are research reference levels, not trading signals.  A
few indicators have commonly used absolute levels; for the rest the dashboard
uses rolling historical percentiles because their absolute scale changes with
market structure and source methodology.
"""

BTC_INDEX_ENDPOINT = "https://data.wublock123.com/api/coinglass/btc-index"
BTC_INDEX_SOURCE = "wu_btc_index"


BTC_INDICATORS = {
    "coinglass/ahr999": {
        "series_id": "AHR999",
        "display_name": "AHR999",
        "unit": "倍",
        "category": "cycle_valuation",
        "description": "根据价格相对200日均线和长期估值模型，观察BTC的周期性估值位置。",
        "use_reference": "用于中长期定投/分批建仓环境，不用于几小时级别择时。",
        "thresholds": [(0.45, "深度低估/历史极端积累"), (1.0, "定投参考线：低于1通常进入可分批定投区间"), (2.0, "偏高估值/降低追涨意愿")],
        "threshold_direction": "lower_is_better",
        "value_field": "ahr999_value",
    },
    "glassnode/001_mvrv-z-score": {
        "series_id": "MVRV_Z_SCORE",
        "display_name": "MVRV Z-Score",
        "unit": "分数",
        "category": "cycle_valuation",
        "description": "(市值-实现市值)除以历史市值波动尺度，用于识别相对高估和低估。",
        "use_reference": "用于判断周期估值是否接近历史极端；需结合NUPL和价格结构。",
        "thresholds": [(0.0, "低于零：历史上偏低估区域"), (3.0, "偏高估值观察区"), (7.0, "历史极端高估参考区")],
        "threshold_direction": "higher_is_risk",
        "value_field": None,
    },
    "coinglass/bitcoin-net-unrealized-profit-loss": {
        "series_id": "NUPL",
        "display_name": "NUPL 未实现净盈亏",
        "unit": "比率",
        "category": "cycle_valuation",
        "description": "(市值-实现市值)/市值，反映全市场未实现盈利或亏损状态。",
        "use_reference": "用于识别市场从亏损、恢复、盈利到过热的周期阶段。",
        "thresholds": [(0.0, "低于零：整体未实现亏损"), (0.25, "希望/恐惧到乐观过渡"), (0.5, "盈利扩张区"), (0.75, "历史上偏过热，需防获利兑现")],
        "threshold_direction": "higher_is_risk",
        "value_field": None,
    },
    "glassnode/004_realized-price": {
        "series_id": "REALIZED_PRICE",
        "display_name": "BTC实现价格",
        "unit": "美元",
        "category": "cycle_valuation",
        "description": "按最后一次链上移动价格计算的全网平均成本价格。",
        "use_reference": "作为中长期成本锚点；BTC价格低于该线表示全网平均持仓处于亏损。",
        "thresholds": [],
        "threshold_direction": "higher_is_risk",
        "value_field": None,
    },
    "coinglass/bitcoin-long-term-holder-supply": {
        "series_id": "LTH_SUPPLY",
        "display_name": "长期持有者供应量",
        "unit": "BTC",
        "category": "holder_behavior",
        "description": "超过155天未发生链上转移的BTC供应量。",
        "use_reference": "关注30日/90日变化：上升偏向囤积，下降可能代表长期筹码释放。",
        "thresholds": [],
        "threshold_direction": "trend_only",
        "value_field": None,
    },
    "coinglass/bitcoin-short-term-holder-supply": {
        "series_id": "STH_SUPPLY",
        "display_name": "短期持有者供应量",
        "unit": "BTC",
        "category": "holder_behavior",
        "description": "小于155天未发生链上转移的BTC供应量。",
        "use_reference": "与LTH供应量结合，观察筹码是否从长期持有者转向短期投机者。",
        "thresholds": [],
        "threshold_direction": "trend_only",
        "value_field": None,
    },
    "coinglass/bitcoin-macro-oscillator": {
        "series_id": "BMO",
        "display_name": "BTC宏观震荡指标",
        "unit": "分数",
        "category": "cycle_valuation",
        "description": "综合MVRV、实现价格、CVDD和收益波动率的宏观周期指标。",
        "use_reference": "用于概括周期环境，不把它当作独立买卖信号；零线和历史分位比固定阈值更重要。",
        "thresholds": [(0.0, "零线：正负周期状态分界参考")],
        "threshold_direction": "higher_is_risk",
        "value_field": "bmo_value",
    },
    "coinglass/bitcoin-vs-m2-growth": {
        "series_id": "BTC_VS_M2",
        "display_name": "BTC vs M2增长",
        "unit": "价格/同比",
        "category": "macro_liquidity",
        "description": "对比BTC价格与全球或美国M2货币供应同比增速。",
        "use_reference": "用于判断宏观流动性是否支持BTC中长期趋势，不用于短线触发。",
        "thresholds": [],
        "threshold_direction": "trend_only",
        "value_field": None,
    },
    "coinglass/fear-greed-history": {
        "series_id": "FEAR_GREED",
        "display_name": "恐惧与贪婪指数",
        "unit": "0-100",
        "category": "sentiment",
        "description": "综合波动率、成交量、社交媒体、调查和市场占比的加密市场情绪指数。",
        "use_reference": "用于识别情绪极端和逆向风险；极度恐惧不等于立即买入，极度贪婪不等于立即做空。",
        "thresholds": [(25, "极度恐惧边界"), (45, "恐惧边界"), (55, "中性边界"), (75, "贪婪边界")],
        "threshold_direction": "higher_is_risk",
        "value_field": None,
    },
    "glassnode/033_asopr": {
        "series_id": "ASOPR",
        "display_name": "aSOPR",
        "unit": "比率",
        "category": "holder_behavior",
        "description": "调整后的已花费输出利润率，反映转移中的BTC总体是盈利还是亏损。",
        "use_reference": "1是关键线：高于1偏向获利兑现，低于1偏向亏损转移；连续性比单日值更重要。",
        "thresholds": [(1.0, "关键线：1以上为盈利转移，1以下为亏损转移")],
        "threshold_direction": "higher_is_risk",
        "value_field": None,
    },
    "glassnode/069_exchange-net-position-change": {
        "series_id": "EXCHANGE_NET_POSITION",
        "display_name": "交易所净头寸变化",
        "unit": "BTC",
        "category": "capital_flow",
        "description": "交易所BTC余额的净变化，反映流入和流出交易所的相对变化。",
        "use_reference": "正值通常代表净流入、潜在卖压增加；负值通常代表净流出，但必须结合交易所归集和标签质量。",
        "thresholds": [(0.0, "零线：净流入/净流出分界")],
        "threshold_direction": "higher_is_risk",
        "value_field": None,
    },
    "glassnode/066_stablecoin-supply-ratio-ssr": {
        "series_id": "SSR",
        "display_name": "稳定币供给比率 SSR",
        "unit": "比率",
        "category": "macro_liquidity",
        "description": "BTC市值与稳定币总供应量的关系，用于观察潜在稳定币购买力。",
        "use_reference": "没有可靠的通用绝对阈值，重点看历史分位和趋势；SSR下降通常表示相对购买力改善。",
        "thresholds": [],
        "threshold_direction": "lower_is_better",
        "value_field": None,
    },
    "glassnode/090_futures-perpetual-funding-rate-all-v2": {
        "series_id": "FUNDING_RATE_ALL",
        "display_name": "全市场永续资金费率",
        "unit": "比率",
        "category": "derivatives_risk",
        "description": "全市场永续合约多空持仓成本。",
        "use_reference": "持续正值且处于高历史分位代表多头拥挤，持续负值且处于低分位代表空头拥挤；单日值不构成方向信号。",
        "thresholds": [(0.0, "零线：多空资金成本方向分界")],
        "threshold_direction": "higher_is_risk",
        "value_field": None,
    },
    "glassnode/087_implied-volatility-index": {
        "series_id": "IMPLIED_VOLATILITY",
        "display_name": "隐含波动率指数",
        "unit": "%",
        "category": "derivatives_risk",
        "description": "期权市场对未来波动的隐含定价。",
        "use_reference": "绝对值受市场阶段影响较大，重点看历史分位和突然上升；高分位意味着止损和仓位风险更重要。",
        "thresholds": [],
        "threshold_direction": "higher_is_risk",
        "value_field": None,
    },
}


def indicator_meta_by_series():
    return {meta["series_id"]: meta for meta in BTC_INDICATORS.values()}
